version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: userdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  auth-service:
    build: ./auth-service
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=mysql+pymysql://user:password@mysql:3306/userdb
      - SECRET_KEY=your-secret-key
    depends_on:
      - mysql

  user-service:
    build: ./user-service
    ports:
      - "8002:8002"
    environment:
      - DATABASE_URL=mysql+pymysql://user:password@mysql:3306/userdb
    depends_on:
      - mysql

  agent-service:
    build: ./agent-service
    ports:
      - "8003:8003"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - knowledge-service

  knowledge-service:
    build: ./knowledge-service
    ports:
      - "8004:8004"
    volumes:
      - knowledge_data:/app/data

  gateway-service:
    build: ./gateway-service
    ports:
      - "8000:8000"
    depends_on:
      - auth-service
      - user-service
      - agent-service
      - knowledge-service

volumes:
  mysql_data:
  knowledge_data: 